server {
    listen 80;

    location /users/ {
        proxy_pass http://users_service:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /applications/ {
        proxy_pass http://applications_service:5001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /environments/ {
        proxy_pass http://environments_service:5002;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /deployments/ {
        proxy_pass http://deployments_service:5003;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location ~ ^/deployments/.+/events/?$ { # regex (~) pour l'exeption vers events
        proxy_pass http://events_service:5004;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /auth/ {
        proxy_pass http://users_service:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

}
